# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_auto_20160622_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evernotecredential',
            name='oauth_token',
            field=models.CharField(max_length=1000),
        ),
    ]
