# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0004_evernotecredential_evernote_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evernotecredential',
            name='evernote_token',
            field=models.CharField(max_length=1000),
        ),
    ]
